name: Publish ProxLock image

concurrency:
  group: Production
  cancel-in-progress: true

on:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write

jobs:
    build-and-push:
        environment:
          name: Production
          url: https://api.proxlock.dev
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@v3
        
        - name: 'Set commit SHA in routes.swift'
          run: |
            sed -i "s|%%REPLACE_HERE_IN_CI%%|${{ github.sha }}|g" Sources/ProxLock/routes.swift

        - name: 'Set image name'
          run: |
            echo "IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY,,}" >> "$GITHUB_ENV"

        - name: 'Login to GitHub Container Registry'
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - run: |
            docker build . \
              -t "$IMAGE_NAME:latest" \
              -t "$IMAGE_NAME:${{ github.sha }}"
            docker push "$IMAGE_NAME:latest"
            docker push "$IMAGE_NAME:${{ github.sha }}"
